### PR TITLE
Update

### PR DESCRIPTION
**Pull request by probonopd**

### CODE REVIEW

**Comment by probonopd** [comment]
Always when GitHub wants me to do stuff on the command line I know that I am screwed. This time it is no different:



__But it does not work:__

```
$ git checkout -b quassel-master AppImage
fatal: Cannot update paths and switch to branch 'quassel-master' at the same time.
Did you intend to checkout 'AppImage' which can not be resolved as commit?
```

**Comment by TheAssassin** [comment]
> `git checkout -b quassel-master AppImage`

This would create a new branch `quassel-master` based on the branch `AppImage`. The latter doesn't exist after cloning, though. That's why you're running into issues.

I hit the same bug, therefore I repeated the `clone` step like `git clone ... -b AppImage` to tell Git I want to get on that branch. Then the rest of the commands worked fine.

**Comment by TheAssassin** [comment]
P.S.: The problem was, as GitHub suggested, in the `.travis.yml`. Instead of amending the Linux part with the linuxdeployqt stuff, he basically overwrote all the contents. Now, upstream changed stuff in the file, and things broke.

I recommend @probonopd to improve the `.travis.yml` therefore. That should further make it possible to send the upstream team a PR one day.

**Comment by probonopd** [comment]
Thank you.

**Comment by probonopd** [comment]
@TheAssassin do you think you could send a PR to upstream and work with them to produce official AppImages? That'd be awesome. Thanks!

**Comment by TheAssassin** [comment]
@probonopd I don't think I have the time to do it, at least not without knowing they would be interested. Maybe you should check with them first whether they'd be interested in an AppImage?

**Comment by probonopd** [comment]
https://github.com/quassel/quassel is one of those projects that have disabled GitHub Issues. If they believe I'm gonna sign up for whatever private system for reporting feature requests this project has set up, they are wrong. Which is an impatient way of saying: Dear Quassel project, if you are ever reading this, please increase the circle of potential collaborators (and bug reporters) by taking part in the large community that is GitHub. Especially so-called "drive-by" contributors (like me) will not sign up for _yet another_ project's _"proprietary"_ (yes, I know!) infrastructure but will be happy to contribute if you allow us to do so on conveniently on GitHub where all the other open source projects are currently living (until everything goes peer-to-peer).

**Pull request merged**
